# **************************************************************************
# *
# * Authors: Alberto Garcia Mena   (alberto.garcia@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import os

import pyworkflow.protocol.constants as cons
from pyworkflow.utils import Message
from pyworkflow import BETA, UPDATED, NEW, PROD
import pyworkflow.utils as pwutils
import pyworkflow.protocol.params as params
from pwem.protocols import EMProtocol
from pyworkflow.protocol import getUpdatedProtocol
import random
import argparse
import tifffile as tiff
import numpy as np
import xmipp3
import time
import shutil
import os
from PIL import Image
import mrcfile
import os

SAMPLE_SIZE = 40
FRAMES_NUM_EER = 50
NORMALIZATION_MAX = 10.0
RESIZE_X = 3680
RESIZE_Y = 3680
ZSTD_COMPRESSION_LEVEL = 8 #ZSTD compression level (1: fast - 22:slow but high compression)

class spaLakePopulator(EMProtocol):
    'This protocol will collect the main data from the SPA workflow and push to the SPALake dataBase those data'
    _label = 'SPALake populator'
    _devStatus = BETA

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    # -------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        """ Define the input parameters that will be used."""

        form.addSection(label='Input Screening')
        form.addParam('dataFromScreening', params.EnumParam, default=1,
                      choices=['True', 'False'],
                      display=params.EnumParam.DISPLAY_HLIST,
                      label='Data from the screening',
                      help='True if data from the screening is on the workflow (Smartscope or SmartEPU plugin).')
        form.addParam('Grids', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfGrids',
                      allowsNull=True,
                      label="Grid ",
                      help="Grid used for acquisition")
        form.addParam('Atlas', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfAtlas',
                      allowsNull=True,
                      label="Atlas",
                      help='Atlas used for acquisition')
        form.addParam('Squares', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfSquares',
                      allowsNull=True,
                      label="Squares",
                      help='Squares used on the picker')
        form.addParam('Holes', params.PointerParam,
                      condition='dataFromScreening==0',
                      pointerClass='SetOfHoles',
                      allowsNull=True,
                      label="Holes",
                      help='Holes used on the acquisition')
        form.addParam('Movies_screening', params.PointerParam,
                      condition='dataFromScreening==0',
                      allowsNull=True,
                      pointerClass='SetOfMoviesSS',
                      label="Movies",
                      help='Movies used on the acquisition generated by the SmartscopeConnection')

        form.addSection(label=Message.LABEL_INPUT)
        form.addParam('Movies', params.PointerParam,
                      condition='dataFromScreening==1',
                      allowsNull=True,
                      pointerClass='SetOfMovies',
                      label="Movies",
                      help='Movies imported by "Import Movies" protocol')

        form.addParam('micrographs', params.PointerParam,
                       pointerClass='SetOfMicrographs',
                       label="Micrographs",
                      allowsNull=True,
                       help='Micrographs generated by aligner')
        form.addParam('CTF', params.PointerParam,
                       pointerClass='SetOfCTF',
                       label="CTFs",
                       allowsNull=True,
                       help='Set of CTF of the set of micrographs')
        form.addParam('TotalClasses2D', params.PointerParam,
                       pointerClass='SetOfClasses2D',
                       allowsNull=True,
                       label="Total Classes2D ",
                       help='Set of the Classes2D ')
        form.addParam('goodClassesOrigin', params.EnumParam, default=0,
                      choices=['Xmipp/Relion', 'Cryoasses', 'Manual'],
                      display=params.EnumParam.DISPLAY_HLIST,
                      label='Protocol generates the good 2D classes',
                      help='Select the protocol the good classes come from. Xmipp and Relion generates setOfClasses2D, Cryoasses SetOfAverages, manual selection generates SetOfClasses2D.')
        form.addParam('goodClasses2DXmippRelion', params.PointerParam,
                       condition='goodClassesOrigin==0',
                       pointerClass='SetOfClasses2D',
                       allowsNull=True,
                       label="Good Classes2D from Relion",
                       help='Set of good Classes2D calculated by Relion ranker')
        form.addParam('goodClasses2DCryoasses', params.PointerParam,
                       condition='goodClassesOrigin==1',
                       pointerClass='SetOfAverages',
                       allowsNull=True,
                       label="Good Classes2D from Cryoasses",
                       help='Set of good Classes2D calculated by Cryoasses ranker')
        form.addParam('goodClasses2DManual', params.PointerParam,
                      condition='goodClassesOrigin==2',
                      pointerClass='SetOfClasses2D',
                      allowsNull=True,
                      label="Good Classes2D from manual selection",
                      help='Set of good Classes2D from manual selection (protUserSubset')
        form.addParam('classes3D', params.PointerParam,
                      pointerClass='SetOfClasses3D',
                      allowsNull=True,
                      label="Classes3D from manual selection",
                      help='Set of good Classes2D from manual selection (protUserSubset')
        form.addParam('volume', params.PointerParam,
                       pointerClass='Volume',
                       allowsNull=True,
                       label="Volume refined",
                       help='Volume refined')

        form.addSection(label=Message.LABEL_EXPORT)
        form.addParam('processingAuthor', params.LabelParam,
                       allowsNull=True,
                       label="Processing author",
                       help='Name of the authors of the processing of the workflow')
        form.addParam('processingDate', params.LabelParam,
                       allowsNull=True,
                       label="Processing date (mm/yy)",
                       help='Date of the processing')

    def _initialize(self):
        # DEBUGALBERTO START
        import os
        fname = "/home/agarcia/Documents/attachActionDebug.txt"
        if os.path.exists(fname):
            os.remove(fname)
        fjj = open(fname, "a+")
        fjj.write('ALBERTO--------->onDebugMode PID {}'.format(os.getpid()))
        fjj.close()
        print('ALBERTO--------->onDebugMode PID {}'.format(os.getpid()))
        import time
        time.sleep(10)
        # DEBUGALBERTO END
        self.moviesPath = os.path.join(os.getcwd(), self._getExtraPath(), 'movies')
        os.makedirs(self.moviesPath, exist_ok=True)
        self.micsPath = os.path.join(os.getcwd(), self._getExtraPath(), 'micrographs')
        os.makedirs(self.micsPath, exist_ok=True)
        self.frameResizedPath = os.path.join(os.getcwd(), self._getExtraPath(), 'frames')
        os.makedirs(self.frameResizedPath, exist_ok=True)
        self.ctfPath = os.path.join(os.getcwd(), self._getExtraPath(), 'CTFs')
        os.makedirs(self.ctfPath, exist_ok=True)

        self.info(f'SAMPLE_SIZE: {SAMPLE_SIZE}')
        self.info(f'FRAMES_NUM_EER: {FRAMES_NUM_EER}')
        self.info(f'NORMALIZATION_MAX: {NORMALIZATION_MAX}')
        self.info(f'RESIZE_x-Y: {RESIZE_X}-{RESIZE_Y}')
        self.info(f'ZSTD_COMPRESSION_LEVEL: {ZSTD_COMPRESSION_LEVEL}\n')


    def _insertAllSteps(self):
        initialize = self._insertFunctionStep(self._initialize,
                                 prerequisites=[],
                                 needsGPU=False)
        listObjects = self.listInputs()
        hierarchy = ["Movies_screening", "Movies", "micrographs", "CTF", "TotalClasses2D", "goodClasses", "3DClasses", "volume"]


        collectMovies = self._insertFunctionStep(self.collectMovies,
                                                 listObjects,
                                                 prerequisites=[initialize],
                                                 needsGPU=False)
        if "Movies_screening" in listObjects:
            collectScreening = self._insertFunctionStep(self.collectScreening,
                                                     prerequisites=[collectMovies],
                                                     needsGPU=False)
        if "micrographs" in listObjects:
            collectMicrographs = self._insertFunctionStep(self.collectMicrographs,
                                                     prerequisites=[collectMovies],
                                                     needsGPU=False)
            if "CTF" in listObjects:
                collectCTF = self._insertFunctionStep(self.collectCTF,
                                                         prerequisites=[collectMicrographs],
                                                             needsGPU=False)

                if "goodClasses" in listObjects:
                        collectGood2DClasses = self._insertFunctionStep(self.collectWithGood2DClasses,
                                                                        listObjects,
                                                                        prerequisites=[collectCTF],
                                                                        needsGPU=False)
                elif "TotalClasses2D" in listObjects:
                    collect2DClasses = self._insertFunctionStep(self.collect2DClasses,
                                                                    listObjects,
                                                                    prerequisites=[collectCTF],
                                                                    needsGPU=False)
                else:
                    return

                if "3DClasses" in listObjects:
                    collect3DClasses = self._insertFunctionStep(self.collect3DClasses,
                                                                    listObjects,
                                                                    prerequisites=[collectCTF],
                                                                    needsGPU=False)
                if "volume" in listObjects:
                        collectVolume = self._insertFunctionStep(self.collectVolume,
                                                                 prerequisites=[collect3DClasses],
                                                                 needsGPU=False)

    # ----------COLLECTION

    def collectMovies(self, listObjects):
        self.info('\n-----------------\nCollecting Movies...')

        if 'Movies_screening' in listObjects:
            movies = self.Movies_screening.get()
        else:
            movies = self.Movies.get()

        # MOVIES
        total_size = len(movies)
        if total_size <= SAMPLE_SIZE:
            self.selectedMovies = movies
        else:
            step = total_size / SAMPLE_SIZE
            self.selectedMovies = [movies[random.randint(int(i * step), int((i + 1) * step) - 1)] for i in range(SAMPLE_SIZE)]
            #self.selectedMovies =  random.sample(listMovies, SAMPLE_SIZE) #Full random
        self.moviesDict = {}
        for m in self.selectedMovies:
            self.moviesDict[m.getMicName()] = {
                'obj': m,
                'lake_ID': None
            }
            shutil.copy2(os.path.join(os.getcwd(), m.getFileName()), os.path.join(self.moviesPath, m.getMicName()))

        # ACQUISITION
        listMovies = list(movies)
        movieToExtract = listMovies[0]
        acq = movieToExtract.getAcquisition()
        self.voltaje = acq.getVoltage()
        self.dosePerFrame = acq.getDosePerFrame()
        self.frames = movieToExtract.getFramesRange()[1]
        self.extension = movieToExtract.getBaseName().split('.')[-1]

        # FRAMES
        self.shapeFrame = []
        for m in self.selectedMovies:
            t0 = time.time()
            frame, frameResizedPath = self.frameExtraction(m)
            t1 = time.time()
            self.shapeFrame.append(self.frameShaping(frame, frameResizedPath))
            t2 = time.time()
            #print(f'Time frameExtraction: {round(t1-t0,1)}s   TimeResize: {round(t2-t1, 1)}s\n')

    def collectScreening(self):
        '''
        Save metadata from screening, each data and the crops of the Squares and Holes
        '''
        self.info('\n-----------------\nCollecting Screening...')
        setOfGrids = self.Grids.get()
        #TODO: todos los parametros de grid subirlos a la base de datos
        setOfAtlas = self.Atlas.get()
        setOfSquares = self.Squares.get()
        setOfHoles = self.Holes.get()
        #TODO: push each Grid to SPALake and collect the ID and push atlas with the ID of the grid generated by SALake

        gridsDict = {}
        for g in setOfGrids:
            gridsDict[g.getGridId()] = {
                'obj': g,
                'lake_ID': None
            }
        atlasDict = {}
        for g in setOfAtlas:
            gridsDict[g.getAtlasId()] = {
                'obj': g,
                'lake_ID': None
            }
        squareDict = {}
        for g in setOfSquares:
            squareDict[g.getSquareId()] = {
                'obj': g,
                'lake_ID': None
            }
        holeDict = {}
        for g in setOfHoles:
            holeDict[g.getHoleId()] = {
                'obj': g,
                'lake_ID': None
            }



    def collectMicrographs(self):
        '''
        The same set than the movies...
        Returns
        -------

        '''
        self.info('\n-----------------\nCollecting Micrographs...')

        setOfMics = self.micrographs.get()
        self.micsDict = {}
        for m in self.moviesDict.values():
            mic = setOfMics.getItem('_micName', m.getBaseName())
            self.micsDict[m.getMicName()] = {
                'obj': mic,
                'lake_ID': None
            }
            shutil.copy2(os.path.join(os.getcwd(), mic.getFileName()), os.path.join(self.micsPath, mic.getBaseName()))

    def collectCTF(self):
        self.info('\n-----------------\nCollecting CTFs...')

        setOfCTFs= self.CTF.get()
        self.CTFDict = {}
        for m in self.micsDict.values():
            ctf = setOfCTFs.getItem('_micObj._micName', m.getBaseName())
            self.CTFDict[m.getMicName()] = {
                'obj': ctf,
                'lake_ID': None
            }
            shutil.copy2(os.path.join(os.getcwd(), ctf.getPsdFile()), os.path.join(self.ctfPath, os.path.basename(ctf.getPsdFile())))


    def collectCoords(self):
        self.info('\n-----------------\nCollecting Coords...')
        setOfCoords = self.coords.get()



    def collect2DClasses(self):
        self.info('\n-----------------\nCollecting collect2DClasses...')
        setOf2DClasses= self.TotalClasses2D.get()
        self.Dict2D = {}
        for p in setOf2DClasses.iterClassItems(): #iterRows
            mic_name = p.getCoordinate().getMicName()



    def collectWithGood2DClasses(self):
        self.info('\n-----------------\nCollecting collectWithGood2DClasses...')


    def collectVolume(self):
        pass


    #----------UTILS
    def listInputs(self):
        listObjects = []

        if self.volume.hasValue() == True:
            listObjects.append('volume')
        if self.classes3D.hasValue() == True:
            listObjects.append('3DClasses')
        if self.goodClasses2DXmippRelion.hasValue() == True:
            listObjects.append('goodClasses')
            listObjects.append('goodClasses2DXmippRelion')
        if self.goodClasses2DCryoasses.hasValue() == True:
            listObjects.append('goodClasses')
            listObjects.append('goodClasses2DCryoasses')
        if self.goodClasses2DManual.hasValue() == True:
            listObjects.append('goodClasses')
            listObjects.append('goodClasses2DManual')
        if self.TotalClasses2D.hasValue() == True:
            listObjects.append('TotalClasses2D')
        if self.micrographs.hasValue() == True:
            listObjects.append('micrographs')
        if self.CTF.hasValue() == True:
            listObjects.append('CTF')
        if self.Movies_screening.hasValue() == True:
            listObjects.append('Movies_screening')
            listObjects.append('Movies')
            if self.Holes.hasValue() == True:
                listObjects.append('Holes')
            if self.Squares.hasValue() == True:
                listObjects.append('Squares')
            if self.Atlas.hasValue() == True:
                listObjects.append('Atlas')
            if self.Grids.hasValue() == True:
                listObjects.append('Grids')
        elif self.Movies.hasValue() == True:
            listObjects.append('Movies')

        return listObjects

    def frameExtraction(self, movie):
        '''
        Extract a single frame the midle one, for any kind of movie, *.tif, *.mrc, *.eer
        For eer extract to have a dose of 1e-/A2'''
        pathMovie = os.path.join(os.getcwd(),  movie.getLocation()[1])
        frame_index = int(self.frames / 2)
        if self.extension == 'eer':
            nameFramePath = os.path.join(os.getcwd(), self._getExtraPath(), movie.getBaseName().replace('.eer', '_middleFrame.tif'))
            frameResizedPath = os.path.join(self.frameResizedPath, movie.getBaseName().replace('.eer', '_frameResized.tif'))
            cmd = f'{int(FRAMES_NUM_EER/2)}@{pathMovie}#{FRAMES_NUM_EER},4K,uint8 -o {nameFramePath}'
            self.runJob('xmipp_image_convert', cmd, env=xmipp3.Plugin.getEnviron())
            with tiff.TiffFile(nameFramePath) as tif:
                frame = tif.pages[0].asarray().astype(np.uint8)
            if os.path.exists(nameFramePath):
                os.remove(nameFramePath)
        elif self.extension in ["tif", "tiff"]:
            frameResizedPath = os.path.join(self.frameResizedPath, movie.getBaseName().replace('.tif', '_frameResized.tif'))
            with tiff.TiffFile(pathMovie) as tif:
                frame = tif.pages[frame_index].asarray().astype(np.uint8)
        elif self.extension == "mrc":
            frameResizedPath = os.path.join(self.frameResizedPath, movie.getBaseName().replace('.mrc', '_frameResized.tif'))
            with mrcfile.open(pathMovie, permissive=True) as mrc:
                data = mrc.data.astype(np.uint8)
                frame = data[frame_index]

        return frame, frameResizedPath

    def frameShaping(self, frame, frameResizedPath):
        '''
        - Normalize (10->255)
        - Crop Square (upperRight)
        - Resize 3680x3680 (Lanczos (sinc(x)*sinc(x/a)

        K2: 3838x3710 (7676x7420 HD)
        K3: 5760x4092 (11520x8184 HD) eer
        Falcon3: 4096x4096
        Falcon4: 4096x4096
        '''
        # --- CROP ---
        img = Image.fromarray(frame)
        w, h = img.size
        if w != h:
            side = min(w, h)
            img = img.crop((0, 0, side, side))

        # --- RESIZE ---
        img_resized = img.resize((RESIZE_X, RESIZE_Y), Image.LANCZOS)
        imgResized = np.array(img_resized)

        # --- NORMALIZATION ---
        scale = 255.0 / NORMALIZATION_MAX
        normFrame = (imgResized * scale).astype(np.uint8)

        # --- COMPRESS ---
        try:
            import imagecodecs
            compression = "zstd"
            compressionargs = {"level": ZSTD_COMPRESSION_LEVEL}
        except ImportError:
            self.warning("[WARNING] imagecodecs not installed ? falling back to LZW")
            compression = "lzw"
            compressionargs = {}


        tiff.imwrite(
            frameResizedPath,
            normFrame,
            compression=compression,
            compressionargs=compressionargs,
        )

    # ----------GENERAL-UTILS

    def _summary(self):
        summary = []
        summaryF = self._getExtraPath("summary.txt")
        if not os.path.exists(summaryF):
            summary.append("No summary file yet.")
        else:
            summaryF = open(summaryF, "r")
            for line in summaryF.readlines():
                summary.append(line.rstrip())
            summaryF.close()
        return summary

    def _validate(self):
        errors = []
        listObjects = self.listInputs()

        def validate_list(obj_list):
            hierarchy = ["Movies", "micrographs", "TotalClasses2D", "goodClasses", "3DClasses", "volume"]
            elements = set(obj_list)

            # Check hierarchical dependencies
            for i, item in enumerate(hierarchy):
                if item in elements:
                    missing = [prev for prev in hierarchy[:i] if prev not in elements]
                    if missing:
                        return False, f"Missing dependencies for '{item}': {missing}"

            # Special rule: Movies_screening requires extra objects
            if "Movies_screening" in elements:
                required = {"Grids", "Atlas", "Squares", "Holes"}
                missing = required - elements
                if missing:
                    return False, f"Movies_screening requires: {list(missing)}"

            return True, "OK"

        valiodator = validate_list(listObjects)
        if valiodator[0] == False:
            errors.append(valiodator[1])

        return errors